services:
  api:
    build:
      context: backend
      dockerfile: src/Api/Dockerfile
    extends:
      file: compose.yaml
      service: api

  web:
    build: frontend
    extends:
      file: compose.yaml
      service: web
