services:
  api:
    image: docker.io/andvant/projecttracker-api:latest
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    extends:
      file: compose.yaml
      service: api

  web:
    image: docker.io/andvant/projecttracker-web:latest
    extends:
      file: compose.yaml
      service: web
