// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjectTracker.Infrastructure.Database;

#nullable disable

namespace ProjectTracker.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260306084550_AddFullNameToUser")]
    partial class AddFullNameToUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("project_tracker")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProjectTracker.Domain.Entities.Attachment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_attachments");

                    b.ToTable("attachments", "project_tracker");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.Comment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_comments");

                    b.HasIndex("IssueId")
                        .HasDatabaseName("ix_comments_issue_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_comments_user_id");

                    b.ToTable("comments", "project_tracker");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.Issue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid")
                        .HasColumnName("assignee_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<int?>("EstimationMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("estimation_minutes");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<int>("Number")
                        .HasColumnType("integer")
                        .HasColumnName("number");

                    b.Property<Guid?>("ParentIssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_issue_id");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("ReporterId")
                        .HasColumnType("uuid")
                        .HasColumnName("reporter_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_issues");

                    b.HasIndex("AssigneeId")
                        .HasDatabaseName("ix_issues_assignee_id");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_issues_key");

                    b.HasIndex("ParentIssueId")
                        .HasDatabaseName("ix_issues_parent_issue_id");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("ix_issues_project_id");

                    b.HasIndex("ReporterId")
                        .HasDatabaseName("ix_issues_reporter_id");

                    b.ToTable("issues", "project_tracker");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.IssueAttachment", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.HasKey("IssueId", "AttachmentId")
                        .HasName("pk_issue_attachment");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_issue_attachment_attachment_id");

                    b.ToTable("issue_attachment", "project_tracker");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.IssueWatcher", b =>
                {
                    b.Property<Guid>("IssueId")
                        .HasColumnType("uuid")
                        .HasColumnName("issue_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("IssueId", "UserId")
                        .HasName("pk_issue_watcher");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_issue_watcher_user_id");

                    b.ToTable("issue_watcher", "project_tracker");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_projects");

                    b.HasIndex("Key")
                        .IsUnique()
                        .HasDatabaseName("ix_projects_key");

                    b.HasIndex("OwnerId")
                        .HasDatabaseName("ix_projects_owner_id");

                    b.ToTable("projects", "project_tracker");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.ProjectAttachment", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("attachment_id");

                    b.HasKey("ProjectId", "AttachmentId")
                        .HasName("pk_project_attachment");

                    b.HasIndex("AttachmentId")
                        .HasDatabaseName("ix_project_attachment_attachment_id");

                    b.ToTable("project_attachment", "project_tracker");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("MemberSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("member_since");

                    b.HasKey("ProjectId", "UserId")
                        .HasName("pk_project_member");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_project_member_user_id");

                    b.ToTable("project_member", "project_tracker");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset>("RegistrationDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registration_date");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", "project_tracker");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.Comment", b =>
                {
                    b.HasOne("ProjectTracker.Domain.Entities.Issue", "Issue")
                        .WithMany("Comments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_issues_issue_id");

                    b.HasOne("ProjectTracker.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comments_users_user_id");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.Issue", b =>
                {
                    b.HasOne("ProjectTracker.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedIssues")
                        .HasForeignKey("AssigneeId")
                        .HasConstraintName("fk_issues_users_assignee_id");

                    b.HasOne("ProjectTracker.Domain.Entities.Issue", "ParentIssue")
                        .WithMany("ChildIssues")
                        .HasForeignKey("ParentIssueId")
                        .HasConstraintName("fk_issues_issues_parent_issue_id");

                    b.HasOne("ProjectTracker.Domain.Entities.Project", "Project")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_projects_project_id");

                    b.HasOne("ProjectTracker.Domain.Entities.User", "Reporter")
                        .WithMany()
                        .HasForeignKey("ReporterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issues_users_reporter_id");

                    b.Navigation("Assignee");

                    b.Navigation("ParentIssue");

                    b.Navigation("Project");

                    b.Navigation("Reporter");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.IssueAttachment", b =>
                {
                    b.HasOne("ProjectTracker.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attachment_attachments_attachment_id");

                    b.HasOne("ProjectTracker.Domain.Entities.Issue", "Issue")
                        .WithMany("Attachments")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_attachment_issues_issue_id");

                    b.Navigation("Attachment");

                    b.Navigation("Issue");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.IssueWatcher", b =>
                {
                    b.HasOne("ProjectTracker.Domain.Entities.Issue", "Issue")
                        .WithMany("Watchers")
                        .HasForeignKey("IssueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_watcher_issues_issue_id");

                    b.HasOne("ProjectTracker.Domain.Entities.User", "User")
                        .WithMany("WatchedIssues")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_issue_watcher_users_user_id");

                    b.Navigation("Issue");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.Project", b =>
                {
                    b.HasOne("ProjectTracker.Domain.Entities.User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_projects_users_owner_id");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.ProjectAttachment", b =>
                {
                    b.HasOne("ProjectTracker.Domain.Entities.Attachment", "Attachment")
                        .WithMany()
                        .HasForeignKey("AttachmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_attachment_attachments_attachment_id");

                    b.HasOne("ProjectTracker.Domain.Entities.Project", "Project")
                        .WithMany("Attachments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_attachment_projects_project_id");

                    b.Navigation("Attachment");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.ProjectMember", b =>
                {
                    b.HasOne("ProjectTracker.Domain.Entities.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_member_projects_project_id");

                    b.HasOne("ProjectTracker.Domain.Entities.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_project_member_users_user_id");

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.Issue", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("ChildIssues");

                    b.Navigation("Comments");

                    b.Navigation("Watchers");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.Project", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Issues");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("ProjectTracker.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedIssues");

                    b.Navigation("Projects");

                    b.Navigation("WatchedIssues");
                });
#pragma warning restore 612, 618
        }
    }
}
